// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.2
// source: pbbp2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_pbbp2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_pbbp2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_pbbp2_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type Frame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SeqID           *uint64                `protobuf:"varint,1,req,name=SeqID" json:"SeqID,omitempty"`
	LogID           *uint64                `protobuf:"varint,2,req,name=LogID" json:"LogID,omitempty"`
	Service         *int32                 `protobuf:"varint,3,req,name=service" json:"service,omitempty"`
	Method          *int32                 `protobuf:"varint,4,req,name=method" json:"method,omitempty"`
	Headers         []*Header              `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty"`
	PayloadEncoding *string                `protobuf:"bytes,6,opt,name=payload_encoding,json=payloadEncoding" json:"payload_encoding,omitempty"`
	PayloadType     *string                `protobuf:"bytes,7,opt,name=payload_type,json=payloadType" json:"payload_type,omitempty"`
	Payload         []byte                 `protobuf:"bytes,8,opt,name=payload" json:"payload,omitempty"`
	LogIDNew        *string                `protobuf:"bytes,9,opt,name=LogIDNew" json:"LogIDNew,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_pbbp2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_pbbp2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_pbbp2_proto_rawDescGZIP(), []int{1}
}

func (x *Frame) GetSeqID() uint64 {
	if x != nil && x.SeqID != nil {
		return *x.SeqID
	}
	return 0
}

func (x *Frame) GetLogID() uint64 {
	if x != nil && x.LogID != nil {
		return *x.LogID
	}
	return 0
}

func (x *Frame) GetService() int32 {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return 0
}

func (x *Frame) GetMethod() int32 {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return 0
}

func (x *Frame) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Frame) GetPayloadEncoding() string {
	if x != nil && x.PayloadEncoding != nil {
		return *x.PayloadEncoding
	}
	return ""
}

func (x *Frame) GetPayloadType() string {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return ""
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetLogIDNew() string {
	if x != nil && x.LogIDNew != nil {
		return *x.LogIDNew
	}
	return ""
}

var File_pbbp2_proto protoreflect.FileDescriptor

const file_pbbp2_proto_rawDesc = "" +
	"\n" +
	"\vpbbp2.proto\x12\x05pbbp2\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x02(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x02(\tR\x05value\"\x92\x02\n" +
	"\x05Frame\x12\x14\n" +
	"\x05SeqID\x18\x01 \x02(\x04R\x05SeqID\x12\x14\n" +
	"\x05LogID\x18\x02 \x02(\x04R\x05LogID\x12\x18\n" +
	"\aservice\x18\x03 \x02(\x05R\aservice\x12\x16\n" +
	"\x06method\x18\x04 \x02(\x05R\x06method\x12'\n" +
	"\aheaders\x18\x05 \x03(\v2\r.pbbp2.HeaderR\aheaders\x12)\n" +
	"\x10payload_encoding\x18\x06 \x01(\tR\x0fpayloadEncoding\x12!\n" +
	"\fpayload_type\x18\a \x01(\tR\vpayloadType\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x1a\n" +
	"\bLogIDNew\x18\t \x01(\tR\bLogIDNewB(Z&content-creator-imm/internal/feishu/pb"

var (
	file_pbbp2_proto_rawDescOnce sync.Once
	file_pbbp2_proto_rawDescData []byte
)

func file_pbbp2_proto_rawDescGZIP() []byte {
	file_pbbp2_proto_rawDescOnce.Do(func() {
		file_pbbp2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbbp2_proto_rawDesc), len(file_pbbp2_proto_rawDesc)))
	})
	return file_pbbp2_proto_rawDescData
}

var file_pbbp2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbbp2_proto_goTypes = []any{
	(*Header)(nil), // 0: pbbp2.Header
	(*Frame)(nil),  // 1: pbbp2.Frame
}
var file_pbbp2_proto_depIdxs = []int32{
	0, // 0: pbbp2.Frame.headers:type_name -> pbbp2.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pbbp2_proto_init() }
func file_pbbp2_proto_init() {
	if File_pbbp2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbbp2_proto_rawDesc), len(file_pbbp2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbbp2_proto_goTypes,
		DependencyIndexes: file_pbbp2_proto_depIdxs,
		MessageInfos:      file_pbbp2_proto_msgTypes,
	}.Build()
	File_pbbp2_proto = out.File
	file_pbbp2_proto_goTypes = nil
	file_pbbp2_proto_depIdxs = nil
}
